In [152]:
import numpy as np

In [153]:
data = np.random.rand(2,4) #Create an multi-dimensional array of size 2*4 with random elements
data

array([[0.17638181, 0.74802037, 0.40852143, 0.77609032],
       [0.69853777, 0.15819175, 0.6937594 , 0.00966084]])

In [154]:
data.shape # Return the shape of the array
data.ndim # Return the dimensions of the array
data.dtype # Returns the datatype of the array

dtype('float64')

# Creating ndarrays

In [155]:
data1 = [1,3,5,7,9] # Consider list or any pthon sequence data structure
arr1 = np.array(data1) # Converts it into array
arr1

array([1, 3, 5, 7, 9])

In [156]:
arr1.ndim # 1
arr1.shape # (5,)
arr1.dtype # int32

dtype('int32')

In [157]:
data2= [[1,3,5,7,9],[0,2,4,6,8]] # Considering nested lists
arr2 = np.array(data2) # Converts it into 2d array
arr2

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8]])

In [158]:
arr2.ndim # 2
arr2.shape # (2,5)
arr2.dtype # int32

dtype('int32')

In [159]:
arr3 = np.zeros((3,3)) # Creates an array wtih elements as 0 with shape as 3*3 or any specified shape
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [160]:
arr4 = np.zeros_like(arr2) #Creates an array with elements as 0 with shape same as array specified
arr4

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [161]:
arr5 = np.ones((4,3))# Creates an array wtih elements as 1 with shape as 4*3 or any specified shape
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [162]:
arr6 = np.ones_like((arr2)) # Creates an array with elements as 1 with shape same as array specified
arr6

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [163]:
arr7 = np.arange(1,10) # Creates a array of numbers from range 1 to 9 (n-1)
arr7 = arr7.reshape(3,3) # reshape -> reshapes the 1D array to specified dimensions if complatible
# also written as arr7 = np.arange(1,10).reshape(3,3)
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
arr8 = np.identity(5) # Creates a square N × N identity matrix (1s on the diagonal and 0s elsewhere)
# another way arr8 = np.eye(5)
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Datatypes for ndarrays

In [165]:
arr9 = np.arange(1,10,2,dtype="int32")
arr9

array([1, 3, 5, 7, 9])

In [166]:
arr9.dtype #Check the datatype of array it is int32

dtype('int32')

In [167]:
arr10 = np.arange(1,10,2,dtype="float32")
arr10

array([1., 3., 5., 7., 9.], dtype=float32)

In [168]:
arr10.dtype #Check the datatype of array it is float32

dtype('float32')

## Datatype Conversion (Typecasting)

In [169]:
int_arr1 = np.array([1,2,3,4,5])
float_arr1 = int_arr1.astype(np.float32) # astype() used for typecasting
float_arr1 # [1., 2., 3., 4., 5.]
float_arr1.dtype # float32

dtype('float32')

In [170]:
float_arr2 = np.array([1.1,2.2,3.3,4.4,5.5]) 
int_arr2 = float_arr2.astype(np.int32)
int_arr2 # [1, 2, 3, 4, 5]
int_arr.dtype # int32

dtype('int32')

# Arithmetic with NumPy Arrays


In [171]:
test_arr = np.arange(1,13).reshape(3,4)
test_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [172]:
test_arr + test_arr # Adding of arrays

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [173]:
test_arr * test_arr # Multiplication of arrays

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [174]:
test_arr ** 0.5 # Square root of array

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [175]:
1/test_arr # Multiplicative inverse of array

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.11111111, 0.1       , 0.09090909, 0.08333333]])

In [176]:
test_arr ** 2 # Square of array

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# Indexing and Slicing

In [177]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
arr[5] # 5th element

5

In [179]:
arr[5:8] # elements from 5 to 7(n-1) inclusive

array([5, 6, 7])

In [180]:
arr[5:8] = 10 # replace 5 to 7 indexed elements with 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [181]:
arr_sliced = arr[5:8] # Slicing the elements
arr_sliced

array([10, 10, 10])

In [182]:
arr_sliced[:] = 100 # Replacing the sliced elements

In [183]:
arr # Change could be noticed the main array when changed in sliced array

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [184]:
arr2D = np.arange(1,10).reshape(3,3)
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
arr2D[1] # Returns 1 indexed array of the 2D array

array([4, 5, 6])

In [186]:
arr2D[1][1] # Returns 1 indexed  element from the 1 indexed array of the 2D array
#arr2D[1,1]

5

## Boolean Indexing

In [187]:
test_data = np.random.randn(4,5)
test_data

array([[ 2.31639382e+00,  2.87418267e-01, -9.75548999e-02,
        -5.98383821e-02,  3.32483006e-01],
       [-1.42364009e+00,  1.96703966e+00, -1.54350060e-01,
        -1.42172952e+00, -1.33399272e+00],
       [-4.21884324e-01,  2.10464359e-03,  1.55447552e+00,
        -2.03822895e-01,  9.54808625e-01],
       [ 1.44008714e+00,  9.40584676e-01,  9.69040371e-01,
        -4.76665761e-01, -9.05725362e-01]])

In [188]:
test_data[test_data<0] = 0 # Set 0 when element < 0

In [189]:
test_data

array([[2.31639382e+00, 2.87418267e-01, 0.00000000e+00, 0.00000000e+00,
        3.32483006e-01],
       [0.00000000e+00, 1.96703966e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 2.10464359e-03, 1.55447552e+00, 0.00000000e+00,
        9.54808625e-01],
       [1.44008714e+00, 9.40584676e-01, 9.69040371e-01, 0.00000000e+00,
        0.00000000e+00]])

# Transpose arrays

In [190]:
arr_new = np.arange(15).reshape((3, 5))
arr_new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [191]:
arr_t = arr_new.T # .T is used to transpose the given matrix
arr_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [192]:
np.dot(arr_new,arr_t) # performing dot product 

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# Universal Functions

In [193]:
eg_arr = np.arange(10)
eg_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.sqrt(eg_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [195]:
np.exp(eg_arr) # Compute the exponent ex of each element

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [196]:
x = np.random.rand(8)
y = np.random.rand(8)

In [197]:
x

array([0.57620533, 0.1440173 , 0.97473429, 0.40214056, 0.61011179,
       0.0950809 , 0.39502684, 0.96751488])

In [198]:
y

array([0.83044571, 0.29414047, 0.69492579, 0.40971843, 0.09841285,
       0.31172315, 0.06419294, 0.30046274])

In [199]:
np.maximum(x,y) # Element-wise maximum

array([0.83044571, 0.29414047, 0.97473429, 0.40971843, 0.61011179,
       0.31172315, 0.39502684, 0.96751488])

In [200]:
np.minimum(x,y) # Element-wise minimum

array([0.57620533, 0.1440173 , 0.69492579, 0.40214056, 0.09841285,
       0.0950809 , 0.06419294, 0.30046274])

In [201]:
rem , whole_part = np.modf(x*6) # Return fractional and integral parts of array as a separate array

In [202]:
rem

array([0.45723199, 0.86410378, 0.84840574, 0.41284336, 0.66067072,
       0.5704854 , 0.37016104, 0.80508925])

In [203]:
whole_part

array([3., 0., 5., 2., 3., 0., 2., 5.])

In [204]:
np.ceil(x) # Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [205]:
np.floor(y) # Compute the „oor of each element (i.e., the largest integer less than or equal to each element)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [206]:
np.add(x,y) # Add corresponding elements in arrays

array([1.40665104, 0.43815776, 1.66966008, 0.81185899, 0.70852463,
       0.40680405, 0.45921978, 1.26797761])

In [207]:
np.subtract(x,y) # Subtract corresponding elements in arrays

array([-0.25424038, -0.15012317,  0.2798085 , -0.00757787,  0.51169894,
       -0.21664225,  0.3308339 ,  0.66705214])

In [208]:
np.multiply(x,y) # Multiply array elements

array([0.47850725, 0.04236132, 0.67736799, 0.1647644 , 0.06004284,
       0.02963892, 0.02535794, 0.29070217])

In [209]:
np.divide(x,y) # divide

array([0.69385069, 0.48962082, 1.40264516, 0.98150468, 6.19951375,
       0.30501713, 6.15374251, 3.22008273])

In [210]:
np.power(x,y) # Raise elements in first array to powers indicated in second array

array([0.63266298, 0.56553006, 0.98237378, 0.68850377, 0.95253629,
       0.4802286 , 0.94212011, 0.99012644])

# Mathematical and Statistical Methods

In [211]:
sm_arr = np.random.randn(4, 5)
sm_arr

array([[ 0.1281662 ,  0.1879981 , -0.67177703, -0.61123313,  1.55003838],
       [-1.14507227,  0.76788993, -0.08312947,  1.2712299 ,  0.80604494],
       [-0.76243892, -1.13211233,  0.81875328,  0.07955336,  2.30709738],
       [ 1.01034862, -0.29724994, -2.85190031,  1.77308568, -0.12912361]])

In [212]:
sm_arr.mean() # mean of the array

0.1508084387502224

In [213]:
sm_arr.sum() # sum of elements of array

3.016168775004448

In [214]:
sm_arr.mean(axis=1) # mean of elements row-wise

array([ 0.11663851,  0.32339261,  0.26217056, -0.09896791])

In [215]:
sm_arr.sum(axis=0)  # sum of elements column-wise

array([-0.76899637, -0.47347424, -2.78805353,  2.51263582,  4.5340571 ])

In [216]:
sm_arr.cumsum(axis=0) # cummulative sum along the row

array([[ 0.1281662 ,  0.1879981 , -0.67177703, -0.61123313,  1.55003838],
       [-1.01690607,  0.95588803, -0.7549065 ,  0.65999677,  2.35608333],
       [-1.77934499, -0.1762243 ,  0.06384678,  0.73955014,  4.66318071],
       [-0.76899637, -0.47347424, -2.78805353,  2.51263582,  4.5340571 ]])

In [217]:
sm_arr.cumprod(axis=1) # cummulative product along the column

array([[ 0.1281662 ,  0.024095  , -0.01618647,  0.00989371,  0.01533562],
       [-1.14507227, -0.87928946,  0.07309487,  0.09292038,  0.074898  ],
       [-0.76243892,  0.8631665 ,  0.70672041,  0.05622199,  0.1297096 ],
       [ 1.01034862, -0.30032607,  0.8565    ,  1.51864789, -0.1960933 ]])

#  Boolean Arrays Methods

In [218]:
barr = np.random.randn(100)
(barr>0).sum()

56

In [219]:
boolarr1 = np.array([True,False,True,False])

In [220]:
boolarr1.all() # checks if every value is True

False

In [221]:
boolarr1.any() #  tests whether one or more values in an array is True

True

# Sorting

In [222]:
rand_arr = np.random.randn(6)
rand_arr

array([ 0.45510306, -1.27009355, -0.8272714 ,  0.32914856,  0.95230691,
       -0.34264816])

In [223]:
rand_arr.sort()
rand_arr

array([-1.27009355, -0.8272714 , -0.34264816,  0.32914856,  0.45510306,
        0.95230691])

# Set Logic

In [224]:
p = np.array([1,2,3,3,4,2,1,5])
q = np.array([1,2,2,1,6,6])

In [225]:
np.unique(p) # Compute the sorted, unique elements in p
np.unique(q) # Compute the sorted, unique elements in q

array([1, 2, 6])

In [226]:
np.intersect1d(p, q) # Compute the sorted, common elements in p and q

array([1, 2])

In [227]:
np.union1d(p, q) # Compute the sorted union of elements

array([1, 2, 3, 4, 5, 6])

In [228]:
np.setdiff1d(p, q) # Set difference, elements in p that are not in q

array([3, 4, 5])